set fish_greeting ""
echo "		>    NEOMATRIX       _         "
echo "		         |                     "
echo "		    pN#g#p#g#g##g#ge           "
echo "		   ################            "
echo "		 _0################!           "
echo "		 4##################Y          "
echo "		 |   ~~#00##0#MMM''M|          "
echo "		        ´gM#M7                "
echo "		|        00Q0        |         "
echo "		##_____g#0##P_______0          "
echo "		##0g__p###04##&,___M#          "
echo "		0######00   ]0#####00          "
echo "		 |\J###0'   '0####4M'          "
echo "		  |\####&##gg##0&  |           "
echo "		'' ##00#####00##'d             "
echo "		%  ##  ~`P#####|##|             "
echo "		M#9#,##  ]#]  *#j,g            "
echo "		l#g`##] @#9                    "
echo "		 ~#0####p##g##                 "
echo "		   @#######   ####             "
echo "		    M0###  ####                "
echo "		      '                        "
